spring:
  application:
    name: spring security 01
  thymeleaf:
    cache: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  output:
    ansi:
      enabled: always
  security:
    user:
      name: user
      password: user123
      roles: USER
server:
  port: 8081

logging:
  level:
    root: info